export class PermissionConstant {
    public static ADMIN_CCO = 'ADMIN_CCO';
    public static ADMIN_ISCV = 'ADMIN_ISCV';
    public static PROFESSIONAL_INTERVIEW_FULL_EDITION = 'PROFESSIONAL_INTERVIEW_FULL_EDITION';
    public static SHOW_IMPERSONNIFICATION = 'SHOW_IMPERSONNIFICATION';
    public static VIEW_PROFESSIONAL_LEVEL = 'VIEW_PROFESSIONAL_LEVEL';
    public static VIEW_STATUTORY_CERTIFICATE = 'VIEW_STATUTORY_CERTIFICATE';
    public static VIEW_LOGBOOK = 'VIEW_LOGBOOK';
    public static EOBS_FULL_EDITION = 'EOBS_FULL_EDITION';
    public static VIEW_EOBSERVATION_ARCHIVE = 'VIEW_EOBSERVATION_ARCHIVE';
}
