export enum NotificationDocumentTypeEnum {
  CONGRATULATION_LETTER = 'CONGRATULATION_LETTER',
  EOBS = 'EOBS',
  CAREER_OBJECTIVE = 'CAREER_OBJECTIVE',
  WAYPOINT = 'WAYPOINT',
  PROFESSIONAL_INTERVIEW = 'PROFESSIONAL_INTERVIEW',
  LOGBOOK = 'LOGBOOK',
  LOGBOOK_CCO = 'LOGBOOK_CCO',
  LOGBOOK_ISCV = 'LOGBOOK_ISCV',
  HR_DOCUMENT = 'HR_DOCUMENT',
  PROFESSIONAL_LEVEL = 'PROFESSIONAL_LEVEL'
}
