export enum urlGroupEnum {
  'CAREER_OBJECTIVE' = 'career_objectives',
  'EOBSERVATION' = 'eobservations',
  'LEG' = 'legs',
  'PNC' = 'pncs',
  'PNC_PHOTO' = 'pnc_photos',
  'ME' = 'me',
  'HELP_ASSET' = 'help_assets',
  'PIN' = 'pin',
  'STATUTORY_CERTIFICATE' = 'statutory_certificate',
  'PNC_SYNCHRO' = 'pnc_synchros',
  'WAYPOINT' = 'waypoints',
  'PROFESSIONAL_LEVEL' = 'professional_levels',
  'ROTATION' = 'rotations',
  'IMPERSONATION_AVAILABLE' = 'check_impersonation_available',
  'USER_PROFILE' = 'user_profiles',
  'USER_PERMISSION' = 'user_permissions',
  'PING' = 'ping',
  'FORMS_INPUT_PARAM' = 'forms_input_params',
  'CONGRATULATION_LETTER' = 'congratulation_letters'
}
