export enum AuthenticationStatusEnum {
    'AUTHENTICATION_KO' = 'AUTHENTICATION_KO',
    'AUTHENTICATION_OK' = 'AUTHENTICATION_OK',
    'INIT_KO' = 'INIT_KO',
    'APPLI_UNAVAILABLE' = 'APPLI_UNAVAILABLE',
    'IMPERSONATE_MODE' = 'IMPERSONATE_MODE',
}
