export enum EntityEnum {
    AUTHENTICATED_USER = 'AUTHENTICATED_USER',
    PNC = 'PNC',
    CAREER_OBJECTIVE = 'CAREER_OBJECTIVE',
    WAYPOINT = 'WAYPOINT',
    ROTATION = 'ROTATION',
    LEG = 'LEG',
    CREW_MEMBER = 'CREW_MEMBER',
    PNC_PHOTO = 'PNC_PHOTO',
    EOBSERVATION = 'EOBSERVATION',
    STATUTORY_CERTIFICATE = 'STATUTORY_CERTIFICATE',
    PROFESSIONAL_LEVEL = 'PROFESSIONAL_LEVEL',
    CONGRATULATION_LETTER = 'CONGRATULATION_LETTER',
    USER_MESSAGE = 'USER_MESSAGE'
}
