export enum RedactionDisplayModeEnum {
    CAREER_OBJECTIVE = 'CAREER_OBJECTIVE',
    PROFESSIONAL_INTERVIEW = 'PROFESSIONAL_INTERVIEW',
    EOBSERVATION = 'EOBSERVATION',
    EXTRA_REDACTION = 'EXTRA_REDACTION'
}
