export enum TabNavEnum {
    PNC_HOME_PAGE = 'PNC_HOME_PAGE',
    PNC_SEARCH_PAGE = 'PNC_SEARCH_PAGE',
    UPCOMING_FLIGHT_LIST_PAGE = 'UPCOMING_FLIGHT_LIST_PAGE',
    HELP_ASSET_LIST_PAGE = 'HELP_ASSET_LIST_PAGE',
    VISITED_PNC = 'VISITED_PNC',
    VISITED_MANAGER = 'VISITED_MANAGER'
}
