export enum TabHeaderEnum {
    // EDOSSIER
    DEVELOPMENT_PROGRAM_PAGE = 'DEVELOPMENT_PROGRAM_PAGE',
    PROFESSIONAL_LEVEL_PAGE = 'PROFESSIONAL_LEVEL_PAGE',
    STATUTORY_CERTIFICATE_PAGE = 'STATUTORY_CERTIFICATE_PAGE',
    CONGRATULATION_LETTERS_PAGE = 'CONGRATULATION_LETTERS_PAGE',
    REDACTIONS_PAGE = 'REDACTIONS_PAGE',
    LOGBOOK_PAGE = 'LOGBOOK_PAGE',
    BUSINESS_INDICATORS_PAGE = 'BUSINESS_INDICATORS_PAGE',
    UPCOMING_FLIGHT_LIST_PAGE = 'UPCOMING_FLIGHT_LIST_PAGE',
    ALTERNANT_SEARCH = 'ALTERNANT_SEARCH',
    HELP_ASSET_LIST_PAGE = 'HELP_ASSET_LIST_PAGE',
    HR_DOCUMENT_PAGE = 'HR_DOCUMENT_PAGE',
    ACTIVITY_PAGE = 'ACTIVITY_PAGE',
    // ADMIN,
    PROFILE_MANAGEMENT_PAGE = 'PROFILE_MANAGEMENT_PAGE',
    APP_VERSION_MANAGEMENT_PAGE = 'APP_VERSION_MANAGEMENT_PAGE',
    USER_MESSAGE_MANAGEMENT_PAGE = 'USER_MESSAGE_MANAGEMENT_PAGE'
}
