export enum EScoreCommentVerbatimEnum {
    POSITIVE_PERSONAL_FEEDBACK_REASON = 'POSITIVE_PERSONAL_FEEDBACK_REASON',
    NEGATIVE_PERSONAL_FEEDBACK_REASON = 'NEGATIVE_PERSONAL_FEEDBACK_REASON',
    SUGGESTIONS = 'SUGGESTIONS'
}