export enum Entity {
    AUTHENTICATED_USER = 'AUTHENTICATED_USER',
    PNC = 'PNC',
    CAREER_OBJECTIVE = 'CAREER_OBJECTIVE',
    WAYPOINT = 'WAYPOINT',
    UPCOMING_ROTATION = 'UPCOMING_ROTATION',
    UPCOMING_LEG = 'UPCOMING_LEG',
    LAST_ROTATION = 'LAST_ROTATION',
    LAST_LEG = 'LAST_LEG'
}
