export enum Entity {
    AUTHENTICATED_USER = 'AUTHENTICATED_USER',
    PNC = 'PNC',
    CAREER_OBJECTIVE = 'CAREER_OBJECTIVE',
    WAYPOINT = 'WAYPOINT',
    ROTATION = 'ROTATION',
    LEG = 'LEG',
    SUMMARY_SHEET = 'SUMMARY_SHEET',
    CREW_MEMBER = 'CREW_MEMBER',
    PNC_PHOTO = 'PNC_PHOTO'
}
